version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./webserver
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=
    volumes:
      - .:/CmdrShepard-webserver
    ports:
      - "3000:3000"
    depends_on:
      - db
  chatbot:
    build: ./chatbot
    command: ruby core.rb
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=
    volumes:
      - .:/CmdrShepard-chatbot
    depends_on:
      - db